import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Di-Tea Bubble Tea
        </h1>
    
      </main>

      <footer className={styles.footer}>
        <a
          href="https://nocxa.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created by{' '}
          <span className={styles.logo}>
            <Image src="/nocxa_title.svg" alt="Nocxa Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
